import type { IconType } from "react-icons";
import {
  LuAccessibility as Accessibility,
  LuActivity as Activity,
  LuAnchor as Anchor,
  LuAppWindow as AppWindow,
  LuArchive as Archive,
  LuArrowRight as ArrowRight,
  LuAtom as Atom,
  LuBadgeCheck as BadgeCheck,
  LuChartColumn as BarChart3,
  LuBeaker as Beaker,
  LuBell as Bell,
  LuBinary as Binary,
  LuBlocks as Blocks,
  LuBookOpen as BookOpen,
  LuBot as Bot,
  LuBoxes as Boxes,
  LuBraces as Braces,
  LuBrain as Brain,
  LuBrainCircuit as BrainCircuit,
  LuBriefcase as Briefcase,
  LuCalculator as Calculator,
  LuCamera as Camera,
  LuCircuitBoard as CircuitBoard,
  LuClipboardList as ClipboardList,
  LuCloud as Cloud,
  LuCloudCog as CloudCog,
  LuCodeXml as Code2,
  LuCog as Cog,
  LuContainer as Container,
  LuCpu as Cpu,
  LuCrosshair as Crosshair,
  LuDatabase as Database,
  LuDownload as Download,
  LuEye as Eye,
  LuFileCode as FileCode,
  LuFileSearch as FileSearch,
  LuFilm as Film,
  LuFingerprint as Fingerprint,
  LuFlaskConical as FlaskConical,
  LuFlame as Flame,
  LuFolder as Folder,
  LuFolderSearch as FolderSearch,
  LuFrame as Frame,
  LuGauge as Gauge,
  LuGlobe as Globe,
  LuGraduationCap as GraduationCap,
  LuHammer as Hammer,
  LuHardDrive as HardDrive,
  LuHeartPulse as HeartPulse,
  LuHourglass as Hourglass,
  LuInbox as Inbox,
  LuInfinity as InfinityIcon,
  LuKeyboard as Keyboard,
  LuKeyRound as KeyRound,
  LuLandmark as Landmark,
  LuLanguages as Languages,
  LuLaptop as Laptop,
  LuLayers as Layers,
  LuLibrary as Library,
  LuLightbulb as Lightbulb,
  LuChartLine as LineChart,
  LuLink as Link,
  LuLock as Lock,
  LuLockKeyhole as LockKeyhole,
  LuMemoryStick as MemoryStick,
  LuMessagesSquare as MessagesSquare,
  LuMicroscope as Microscope,
  LuMonitor as Monitor,
  LuMonitorSmartphone as MonitorSmartphone,
  LuMousePointerClick as MousePointerClick,
  LuNetwork as Network,
  LuPaintBucket as PaintBucket,
  LuPackage as Package,
  LuPenTool as PenTool,
  LuChartPie as PieChart,
  LuPlay as Play,
  LuPlug as Plug,
  LuPresentation as Presentation,
  LuPuzzle as Puzzle,
  LuRadar as Radar,
  LuRadio as Radio,
  LuRepeat as Repeat,
  LuRefreshCw as RefreshCw,
  LuRocket as Rocket,
  LuRoute as Route,
  LuScale as Scale,
  LuScanLine as ScanLine,
  LuSearch as Search,
  LuServer as Server,
  LuServerCog as ServerCog,
  LuSettings as Settings,
  LuShapes as Shapes,
  LuSheet as Sheet,
  LuShield as Shield,
  LuShieldAlert as ShieldAlert,
  LuShieldCheck as ShieldCheck,
  LuShuffle as Shuffle,
  LuSigma as Sigma,
  LuSiren as Siren,
  LuSlidersHorizontal as SlidersHorizontal,
  LuSmartphone as Smartphone,
  LuSparkles as Sparkles,
  LuTable as Table,
  LuTerminal as Terminal,
  LuTestTube as TestTube,
  LuTimer as Timer,
  LuType as Type,
  LuUsers as Users,
  LuUserCheck as UserCheck,
  LuWaypoints as Waypoints,
  LuWebhook as Webhook,
  LuWorkflow as Workflow,
  LuWrench as Wrench,
  LuZap as Zap,
  LuLayoutGrid as LayoutGrid,
  LuLayoutTemplate as LayoutTemplate,
} from "react-icons/lu";

/**
 * Icônes sémantiques (Lucide, licence ISC) pour les compétences qui sont
 * des concepts génériques sans logo de marque : chaque carte du roadmap
 * a désormais une icône pertinente, sans logo inventé.
 */
export const CONCEPT_ICONS: Record<string, IconType> = {
  // Informatique — fondations
  "culture-info": BookOpen,
  algorithms: Binary,
  "data-structures": Boxes,
  http: Globe,
  networks: Network,
  rest: Plug,
  webhooks: Webhook,
  databases: Database,
  sql: Table,
  accessibility: Accessibility,
  responsive: MonitorSmartphone,
  flexbox: LayoutTemplate,
  "css-grid": LayoutGrid,
  "css-animations": Sparkles,
  dom: Braces,
  "async-js": Hourglass,
  "fetch-api": Download,
  "js-modules": Package,
  "react-hooks": Puzzle,
  "react-state": Layers,
  "react-forms": ClipboardList,
  testing: FlaskConical,
  "web-perf": Gauge,
  "frontend-archi": Blocks,
  fullstack: AppWindow,
  "react-native": Smartphone,
  electronics: CircuitBoard,
  embedded: Cpu,
  robotics: Bot,
  sensors: Radio,
  "control-systems": RefreshCw,
  // IA / Data
  numpy: Sigma,
  pandas: Sheet,
  statistics: BarChart3,
  "machine-learning": Brain,
  "scikit-learn": Cog,
  pytorch: Flame,
  "deep-learning": Waypoints,
  transformers: Repeat,
  llms: Bot,
  rag: FileSearch,
  "computer-vision": Eye,
  nlp: Languages,
  mlops: Workflow,
  maths: Calculator,
  "llm-systems": BrainCircuit,
  "ai-safety": Scale,
  // DevOps
  networking: Network,
  cicd: Cog,
  "container-registry": Container,
  helm: Anchor,
  "k8s-operators": SlidersHorizontal,
  ansible: Play,
  prometheus: Activity,
  // Data engineer
  "platform-engineering": ServerCog,
  "data-engineering": HardDrive,
  rabbitmq: Inbox,
  "data-science": Microscope,
  analytics: PieChart,
  make: Wrench,
  zapier: Zap,
  "api-integration": Link,
  "data-viz": LineChart,
  eda: Search,
  experimentation: Beaker,
  "feature-engineering": Shapes,
  storytelling: Presentation,
  deployment: Rocket,
  // Cybersécurité
  cryptography: KeyRound,
  "web-security": Shield,
  owasp: ShieldAlert,
  authentication: Lock,
  cybersecurity: ShieldCheck,
  pentesting: Crosshair,
  siem: Radar,
  "incident-response": Siren,
  "system-security": LockKeyhole,
  pentest: Crosshair,
  soc: Bell,
  forensics: FolderSearch,
  "secure-coding": BadgeCheck,
  "cloud-security": CloudCog,
  governance: Landmark,
  // Robotique
  physique: Atom,
  electronique: CircuitBoard,
  mecanique: Hammer,
  "systemes-embarques": MemoryStick,
  controle: SlidersHorizontal,
  perception: Camera,
  planification: Route,
  integration: Blocks,
  ros: Cpu,
  // Frontend
  "state-management": Archive,
  performance: Gauge,
  "frontend-architecture": Blocks,
  "design-systems": Library,
  // Backend
  "api-rest": Server,
  auth: UserCheck,
  "testing-api": TestTube,
  caching: Timer,
  messaging: MessagesSquare,
  observability: ScanLine,
  "system-design": Network,
  // DevOps (pratiques)
  scripting: Terminal,
  "ci-cd": Cog,
  cloud: Cloud,
  iac: FileCode,
  monitoring: HeartPulse,
  devsecops: Fingerprint,
  // UX / Design
  "design-thinking": Lightbulb,
  typographie: Type,
  couleur: PaintBucket,
  "ui-design": Monitor,
  "ux-research": Users,
  wireframing: PenTool,
  prototypage: MousePointerClick,
  "design-system": Library,
  "accessibilite-design": Accessibility,
  "motion-design": Film,
  portfolio: Briefcase,
  // TypeScript
  installation: Laptop,
  tsc: Cog,
  tsconfig: Settings,
  editeur: Keyboard,
  "types-base": Type,
  interfaces: Frame,
  fonctions: Code2,
  unions: Shuffle,
  generiques: InfinityIcon,
  "utility-types": Package,
  "types-avances": GraduationCap,
  modules: Folder,
  strict: BadgeCheck,
  outillage: Wrench,
  migration: ArrowRight,
};
